version: "3"
services:
  api-gateway:
    build:
      context: "."
      dockerfile: "./api-gateway/Dockerfile"
    depends_on:
      - websocket
    ports:
      - 7000:7000
    volumes:
      - ./api-gateway:/opt/app
    environment:
      - CHANNELS_SERVICE_URI=http://websocket:8989

  websocket:
    build:
      context: "."
      dockerfile: "./websocket/Dockerfile"
    depends_on:
      - websocket-service-db
    environment:
      - DB_URI=mysql://root:password@websocket-service-db/db?charset=UTF8
    ports:
      - 8989:8989
    volumes:
      - ./websocket:/opt/app

  websocket-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABSE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7205:3306